Repository StevensSEC/stevens-web-extension, pull requests merged in 2020-03, with the labels that each got.

#27 Store token
  src/features/canvas/CanvasIntegration.ts
  src/options.pug
  src/options.ts
Labels: feature, workflow

#28 Free rooms refactor
  src/background.ts
  src/features/FreeRooms/FreeRooms.ts
  src/popup.pug
Labels: workflow

#30 New extension icon!
  src/assets/icon128.png
  src/assets/icon16.png
  src/assets/icon48.png
  src/background.ts
  src/manifest.json
  webpack.config.ts
Labels: ui

#29 New libraries, duckbills, and meal swipes
  .eslintrc.json
  .gitignore
  package.json
  src/background.ts
  src/content.ts
  src/features/Canvas/CanvasDisplay.pug
  src/features/Canvas/CanvasIntegration.ts
  src/features/Features.md
  src/features/MyStevens/MyStevens.ts
  src/features/MyStevens/MyStevensDisplay.pug
  src/features/TempBookmarks/AddTempBookmark.pug
  src/features/TempBookmarks/TemporaryBookmarks.ts
  src/features/canvas/CanvasDisplay.pug
  src/manifest.json
  src/options.pug
  src/options.ts
  src/popup.pug
  src/popup.ts
  src/shared/utility.ts
  webpack.config.ts
  yarn.lock
Labels: feature, workflow

#33 Challenges
  challenges/01_Canvas.md
  challenges/02_Popups.md
  challenges/images/canvas_token.png
  challenges/images/popup.png
Labels: api, documentation
